---
- name: install docker
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: 安装 docker  参考： https://blog.hellojukay.cn/2019/02/26/20190227/
        shell: echo https://blog.hellojukay.cn/2019/02/26/20190227/
        tags: [docker]
      - name: remove docker.io
        shell: yum remove docker docker-client   docker-client-latest   docker-common   docker-latest   docker-latest-logrotate   docker-logrotate   docker-selinux   docker-engine-selinux   docker-engine  -y
        tags: [docker]
      - name: 安装 docker 依赖
        shell: yum install -y yum-utils device-mapper-persistent-data lvm2
        tags: [docker]
      - name: 添加 docker-ce 源
        get_url:
            url: "{{ item }}"
            dest: /etc/yum.repos.d/
        with_items:
            - http://mirrors.aliyun.com/repo/Centos-7.repo
            - http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        tags: [docker]
      - name: install latest docker-ce
        yum:
            name: docker-ce
            state: latest
        tags: [docker]
      - name: upload /etc/docker/daemon.json
        copy:
            src: daemon.json
            dest: /etc/docker/daemon.json
            force: yes
        tags: [docker]
      - name: start docker service
        systemd:
            name: docker
            state: restarted
            enabled: yes
        tags: [docker]

- name: install kubeadm  
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: upload kubernetes.repo
        copy:
            src: kubernetes.repo
            dest: /etc/yum.repos.d/kubernetes.repo
        tags: [kubeadm]
      - name: install kubeadm
        yum:
            name: kubeadm
            state: latest
        tags: [kubeadm]

- name: sysnc docker image
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: install git
        yum:
            name: git
            state: present
        tags: [sync-image]
      - name: git clone https://github.com/hellojukay/k8s-sync.git
        git:
            repo: https://github.com/hellojukay/k8s-sync.git
            dest: /tmp/k8s-sync/
            version: v1.18.5
        tags: [sync-image]
      - name: pull image
        shell: perl pull.pl
        args:
            chdir: /tmp/k8s-sync/
        register: pull
        tags: [sync-image]
      - name: show pull logs
        debug: var=pull.stdout_lines
        tags: [sync-image]

- name: set system
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: stop firewalld
        systemd:
            name: firewalld
            state: stopped
            enabled: false
        tags: [system]

- name: join master
  hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: join maser
        shell:   kubeadm join 10.249.216.99:443 --token jupb6p.gzilh71ec9fq3e9e --discovery-token-ca-cert-hash sha256:a911c64eddcde82978e24d472c7f82debb021eadc34ad00cea75fe9259040811 --control-plane --certificate-key 5dc79c4fd8089b2987513d840cccf512f42304da8769e9bbbb37aa964b95689d
        tags: [join]
- name: join worker
  hosts: worker
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: join worker
        shell: kubeadm join 10.249.216.99:443 --token jupb6p.gzilh71ec9fq3e9e --discovery-token-ca-cert-hash sha256:a911c64eddcde82978e24d472c7f82debb021eadc34ad00cea75fe9259040811 
        tags: [join]
